spring:
  mail:
    host: localhost
    port: 1025
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false
      mail.debug: true  
  thymeleaf:
    cache: false         

app:
  mail:
    from: no-reply@local.test
